services:
  kafka:
    image: confluentinc/cp-kafka:8.0.2
    container_name: kafka-kraft
    hostname: kafka-kraft
    restart: always
    ports:
      - "9092:9092"   # External access
      - "9101:9101"   # JMX monitoring
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Listener configuration
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka-kraft:29092,CONTROLLER://kafka-kraft:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-kraft:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-kraft:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Cluster and topic settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

      # Cluster identity (you can generate your own with uuidgen)
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      # JMX settings (for monitoring)
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

    volumes:
      - ./kafka-data:/var/lib/kafka/data
